# Overview of Python

## Python functions, types and sequences, strings

In [1]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [2]:
x = "changed"
print(x[0:2])


ch


In [3]:
x[-1]

'd'

In [4]:
x[-2:-1]

'e'

In [5]:
4 in [1, 2, 4]
[1, 2] in [1, 2, 4]

False

In [6]:
"remain" + str("0")

'remain0'

In [7]:
x = {"Chris Brooks": "BrooksCh@gmail.com", "Bill Gates": "BillG@gmail.com"}
x["Chris Brooks"]

'BrooksCh@gmail.com'

In [8]:
x["Julia Me"] = None

In [9]:
for name, email in x.items():
    print(name)
    print(email)

Chris Brooks
BrooksCh@gmail.com
Bill Gates
BillG@gmail.com
Julia Me
None


In [10]:
#unpacking
x = ("Chris", "Brooks", "BrooksCh@gmail.com")

In [11]:
#unpack variables through assignment
fname, lname, email = x

In [12]:
fname

'Chris'

In [13]:
#Almost everything in Python is an object, with its properties and methods. A Class is like an object constructor, or "blueprint" for creating objects.

class Person:
    department = "School of Information"
    year = 2000

print(Person().department)

School of Information


In [14]:
def set_name(self, new_name):
    self.name = new_name
def set_location(self, new_location):
    self.location = new_location

## Functions, split()

In [15]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

# Return Dr. Lastname

def split_name(person):
    title = person.split()[0]
    surname = person.split()[-1]
    return title + " " + surname
    #or return '{} {}'.format(title, surname)
    #or return " ".join([title, surname])

list(map(split_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

In [16]:
for person in people:
    print(split_name(person))

Dr. Brooks
Dr. Collins-Thompson
Dr. Vydiswaran
Dr. Romero


In [17]:
list(map(split_name, people))
#option 1
for person in people:
    print(split_name(person) == (lambda x:x.split()[0] + " " + x.split()[-1]))

#option 2
list(map(split_name, people)) == list(map(lambda person: person.split()[0] + " " + person.split()[-1], people))


False
False
False
False


True

In [18]:
my_list = []
for number in range(0, 10):
    if number % 2 == 0:
        my_list.append(number)
        
my_list

[0, 2, 4, 6, 8]

## List comprehension

In [19]:
#list comprehension
my_list = [number for number in range(0, 10) if number % 2 == 0]
my_list

[0, 2, 4, 6, 8]

In [20]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst



In [21]:
#list comprehension method
times_tables() == [i*j for i in range(10) for j in range(10)]

True

In [22]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

# for i in lowercase:
#     for j in lowercase:
#         for k in digits:
#             for l in digits:
#                 print(i + j + k + l)

[i + j + k + l for i in lowercase for j in lowercase for k in digits for l in digits][:50]

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09',
 'aa10',
 'aa11',
 'aa12',
 'aa13',
 'aa14',
 'aa15',
 'aa16',
 'aa17',
 'aa18',
 'aa19',
 'aa20',
 'aa21',
 'aa22',
 'aa23',
 'aa24',
 'aa25',
 'aa26',
 'aa27',
 'aa28',
 'aa29',
 'aa30',
 'aa31',
 'aa32',
 'aa33',
 'aa34',
 'aa35',
 'aa36',
 'aa37',
 'aa38',
 'aa39',
 'aa40',
 'aa41',
 'aa42',
 'aa43',
 'aa44',
 'aa45',
 'aa46',
 'aa47',
 'aa48',
 'aa49']

## ndim()

In [23]:
import numpy as np
import math

In [24]:
#array
a = np.array([1.3,2,3])
print(a)
print(a.ndim)


[1.3 2.  3. ]
1


In [25]:
#list
b = np.array([[1,2,3],[4,5,6]])
b
#length of each dimension
b.shape

(2, 3)

In [26]:
a.dtype.name

'float64'

In [27]:
c = np.zeros((2,3))
print(c)

d = np.ones((2, 3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
np.random.rand(2,3)

array([[0.70346005, 0.37102493, 0.30615958],
       [0.03885756, 0.08406576, 0.85008846]])

## arange() sequence

In [29]:
np.arange(10, 50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [30]:
np.linspace(0, 2, 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

## Slicing

In [31]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
a[:2]

array([[1, 2],
       [3, 4]])

In [33]:
a[:2, 1:3][0,0]

np.int64(2)

In [34]:
# shape of list is preserved
# wines[:, 0:1]

## Regex

In [35]:
import re

In [36]:
text = "Amy works diligently. Amy gets good grades. Our student Amy is successful."
re.findall("Amy", text)

['Amy', 'Amy', 'Amy']

### Quantifiers

In [37]:
# e.g. *, ?, m{n} describe patterns
# search for text that begins with Amy
re.search("^Amy", text)

<re.Match object; span=(0, 3), match='Amy'>

In [38]:
grades = "ACAAAAABCBCBADA"
re.findall("B", grades)

['B', 'B', 'B']

In [39]:
re.findall("[AB]", grades)

['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A']

In [40]:
re.findall("[A][B-D]", grades)

['AC', 'AB', 'AD']

In [41]:
re.findall("AB|AC", grades)

['AC', 'AB']

In [42]:
re.findall("[^A]", grades)
#use caret

['C', 'B', 'C', 'B', 'C', 'B', 'D']

### Quantifiers

In [43]:
grades = "ACAAAAABCBCBAA"
re.findall("A{2,10}", grades) #quantifier with min and max e{m,n}

['AAAAA', 'AA']

In [44]:
re.findall("A{2,2}", grades)

['AA', 'AA', 'AA']

In [45]:
re.findall("A{2}", grades)

['AA', 'AA', 'AA']

In [46]:
#Is there a decreasing trend within the student's grades?
re.findall("A{1,10}B{1,10}C{1,10}", grades)

['AAAAABC']

In [47]:
# headers that end with [edit]
# re.findall("[a-zA-Z]{1,100}][edit\]", wiki)
# \w means any word character
# re.findall("[\w]{1,100}][edit\]", wiki)
# re.findall("[\w]*\{1,100}][edit\]", wiki)
# re.findall("[\w ]*\{1,100}][edit\]", wiki)
# 3for title in re.findall("[\w]*\[edit\]", wiki)

In [48]:
### Groups
# for item in re.finditer("([\w]*)(\[edit\])", wiki):
#     print(item.group(1))

In [49]:
# ?P<> syntax: parenthesis starts the group, ?P indicates extension to basic regexes, <name> is dict key we want wrapped in <>.
# for item in re.finditer("(?P<title>[\w]*)(P<edit_link>\[edit\])")
     # print(item.groupdict()["title"])
# print(item.groupdict())

In [50]:
# a . for any single character which is not a newline
# a \d for any digit
# a \s for any whitespace character, like spaces and tabs
# a * is a quantifier that matches 0 or more occurences of the character

### Look-ahead and look-behind

In [51]:
# match two groups, first named title and will have any amount of whitespace or regex. second will be characters
# but we don't actually want the edit put into our output match objects

# for item in re.finditer("(?P<title>[\w ]+)(?=\[edit\])", wiki):

## Quiz

In [52]:
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)

In [53]:
result

['bat', 'bot']

In [54]:
s = 'ACBCAC'
re.findall('AC', s)

['AC', 'AC']

In [55]:
print(np.linspace(1,4,4).shape)
print(np.random.rand(4).shape)
print(np.array([[1, 2, 3, 4]]).shape)

(4,)
(4,)
(1, 4)


In [56]:
old = np.array([[0, 1, 5], [1, 1, 1]])
new = old
new[0, 2:]
#new[0:1, 0:1]

array([5])

In [57]:
s = 'ACBCAC'
re.findall('^[AC]', s)

['A']

In [58]:
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
result

['A', 'AA', 'AA', 'AA', 'A']